import { spawn } from 'child_process'
import { mkdir, writeFile } from 'fs/promises'
import { join } from 'path'
import { APPS } from '@shared/catalog/apps'
import type { AdminBundleOptions } from '@shared/types/system'
import { profilesRepo } from '../db/repositories/profiles.repo'

function wingetDownload(wingetId: string, destDir: string): Promise<{ ok: boolean; error?: string }> {
  return new Promise((resolve) => {
    const child = spawn(
      'winget',
      [
        'download',
        '--id',
        wingetId,
        '-e',
        '-d',
        destDir,
        '--accept-package-agreements',
        '--accept-source-agreements',
        '--disable-interactivity'
      ],
      { windowsHide: true }
    )
    let stderr = ''
    child.stderr.on('data', (d) => (stderr += d.toString()))
    child.on('error', (err) => resolve({ ok: false, error: err.message }))
    child.on('close', (code) => resolve({ ok: code === 0, error: code === 0 ? undefined : stderr.slice(-300) }))
  })
}

/** Builds a self-contained "company setup" bundle: a manifest, a PowerShell deployment
 *  script that installs the same app set via winget on any target machine (run it via
 *  GPO/Intune/PsExec — that's the real "deploy on multiple PCs" story for a winget-based
 *  tool, since winget itself has no push-install mechanism), and, optionally, the actual
 *  installer binaries pre-downloaded via `winget download` for offline use. */
export const adminBundleService = {
  async generateBundle(options: AdminBundleOptions): Promise<string> {
    const profiles = options.profileIds.map((id) => profilesRepo.get(id)).filter((p): p is NonNullable<typeof p> => !!p)
    if (profiles.length === 0) throw new Error('No valid profiles selected')

    const appIds = [...new Set(profiles.flatMap((p) => p.apps.map((a) => a.appId)))]
    const apps = appIds.map((id) => APPS.find((a) => a.id === id)).filter((a): a is NonNullable<typeof a> => !!a)

    const bundleDir = join(options.outputDir, sanitizeFolderName(options.name))
    await mkdir(bundleDir, { recursive: true })

    const manifest = {
      name: options.name,
      generatedAt: new Date().toISOString(),
      profiles: profiles.map((p) => ({ id: p.id, name: p.name })),
      apps: apps.map((a) => ({ id: a.id, name: a.name, wingetId: a.wingetId, chocoId: a.chocoId }))
    }
    await writeFile(join(bundleDir, 'manifest.json'), JSON.stringify(manifest, null, 2), 'utf-8')

    const script = buildDeployScript(apps)
    await writeFile(join(bundleDir, 'deploy.ps1'), script, 'utf-8')

    if (options.includeOfflineInstallers) {
      const installersDir = join(bundleDir, 'installers')
      await mkdir(installersDir, { recursive: true })
      const failures: string[] = []
      for (const app of apps) {
        if (!app.wingetId) continue
        const result = await wingetDownload(app.wingetId, installersDir)
        if (!result.ok) failures.push(`${app.name}: ${result.error ?? 'unknown error'}`)
      }
      if (failures.length) {
        await writeFile(join(bundleDir, 'download-failures.txt'), failures.join('\n'), 'utf-8')
      }
    }

    return bundleDir
  }
}

function sanitizeFolderName(name: string): string {
  return name.replace(/[<>:"/\\|?*]/g, '-').trim() || 'setupforge-bundle'
}

function buildDeployScript(apps: { name: string; wingetId?: string }[]): string {
  const lines = [
    '# SetupForge deployment script — generated by Admin Mode.',
    '# Run as Administrator on each target machine (or push via GPO/Intune/PsExec).',
    '$ErrorActionPreference = "Continue"',
    ''
  ]
  for (const app of apps) {
    if (!app.wingetId) {
      lines.push(`# Skipped "${app.name}" — no winget package id on file.`)
      continue
    }
    lines.push(`Write-Host "Installing ${app.name}..."`)
    lines.push(
      `winget install --id ${app.wingetId} -e --silent --accept-package-agreements --accept-source-agreements`
    )
    lines.push('')
  }
  lines.push('Write-Host "Deployment complete."')
  return lines.join('\n')
}
